name: Generate Snake Animation

on:
  # Run automatically every day
  schedule:
    - cron: "0 0 * * *"
  
  # Run on push to main branch
  push:
    branches:
      - main
      
  # Allow manual workflow run
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v3
      
      # Generate snake animation from real GitHub contribution data
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Sanalemba991
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Push the generated content to the output branch
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          # Use your personal access token instead of GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.PAT }}
